# Generated by Django 2.2.17 on 2026-01-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_releasestatistics_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'receptor_modality',
            },
        ),
    ]
