# Generated by Django 2.2.17 on 2026-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactnetwork', '0016_auto_20230216_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactingpeptideresiduepair',
            name='buried_sasa_peptide',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interactingpeptideresiduepair',
            name='buried_sasa_receptor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interactingpeptideresiduepair',
            name='surface_complementarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
