# Generated by Django 2.2.17 on 2025-09-16 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0020_auto_20250318_1242'),
        ('alignment', '0015_auto_20240316_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptorSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.PositiveSmallIntegerField()),
                ('similarity', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor_similarity_as_ref', to='protein.Protein')),
                ('protein_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor_similarity_as_target', to='protein.Protein')),
            ],
            options={
                'db_table': 'alignment_receptorsimilarity',
            },
        ),
        migrations.AddConstraint(
            model_name='receptorsimilarity',
            constraint=models.UniqueConstraint(fields=('protein_ref', 'protein_target'), name='uniq_receptor_similarity_pair'),
        ),
        migrations.AddConstraint(
            model_name='receptorsimilarity',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, protein_ref=django.db.models.expressions.F('protein_target')), name='check_ref_ne_target'),
        ),
    ]
