# Generated by Django 2.2.17 on 2025-09-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0016_auto_20250916_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptorsimilarity',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='receptorsimilarity',
            name='protein_ref',
            field=models.ForeignKey(db_column='ref', on_delete=django.db.models.deletion.CASCADE, related_name='receptor_similarity_as_ref', to='protein.Protein'),
        ),
        migrations.AlterField(
            model_name='receptorsimilarity',
            name='protein_target',
            field=models.ForeignKey(db_column='target', on_delete=django.db.models.deletion.CASCADE, related_name='receptor_similarity_as_target', to='protein.Protein'),
        ),
    ]
