# Generated by Django 2.2.17 on 2025-09-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0020_auto_20250318_1242'),
        ('alignment', '0017_auto_20250916_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptorsimilarity',
            name='ref_class',
            field=models.ForeignKey(blank=True, db_column='ref_class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_as_ref_class', to='protein.ProteinFamily'),
        ),
        migrations.AddField(
            model_name='receptorsimilarity',
            name='target_class',
            field=models.ForeignKey(blank=True, db_column='target_class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_as_target_class', to='protein.ProteinFamily'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['ref_class', 'target_class'], name='rs_ref_tgt_cls_idx'),
        ),
    ]
