# Generated by Django 2.2.17 on 2025-09-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0018_auto_20250924_1147'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='receptorsimilarity',
            name='rs_ref_tgt_cls_idx',
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['ref_class', 'target_class', 'identity'], name='rs_cls_id_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['ref_class', 'target_class', 'similarity'], name='rs_cls_sim_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['target_class', 'ref_class', 'identity'], name='rs_cls_id_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='receptorsimilarity',
            index=models.Index(fields=['target_class', 'ref_class', 'similarity'], name='rs_cls_sim_rev_idx'),
        ),
    ]
