ww# Generated by Django 2.2.17 on 2024-11-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0021_auto_20240223_1135'),
        ('ligand', '0025_auto_20230831_1052'),
        ('common', '0006_releasestatistics_database'),
        ('drugs', '0003_drugs_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=8, null=True)),
                ('slug', models.CharField(max_length=255, null=True, unique=True)),
                ('level', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.Indication')),
                ('uri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.WebLink')),
            ],
            options={
                'db_table': 'indication',
            },
        ),
        migrations.CreateModel(
            name='IndicationAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_score', models.FloatField(max_length=7, null=True)),
                ('ot_genetics_portal', models.FloatField(max_length=7, null=True)),
                ('gene_burden', models.FloatField(max_length=7, null=True)),
                ('clingen', models.FloatField(max_length=7, null=True)),
                ('gene2phenotype', models.FloatField(max_length=7, null=True)),
                ('orphanet', models.FloatField(max_length=7, null=True)),
                ('genomics_england', models.FloatField(max_length=7, null=True)),
                ('uniprot_literature', models.FloatField(max_length=7, null=True)),
                ('uniprot_variants', models.FloatField(max_length=7, null=True)),
                ('sysbio', models.FloatField(max_length=7, null=True)),
                ('cancer_gene_census', models.FloatField(max_length=7, null=True)),
                ('cancer_biomarkers', models.FloatField(max_length=7, null=True)),
                ('intogen', models.FloatField(max_length=7, null=True)),
                ('eva', models.FloatField(max_length=7, null=True)),
                ('eva_somatic', models.FloatField(max_length=7, null=True)),
                ('chembl', models.FloatField(max_length=7, null=True)),
                ('slapenrich', models.FloatField(max_length=7, null=True)),
                ('crispr', models.FloatField(max_length=7, null=True)),
                ('crispr_screen', models.FloatField(max_length=7, null=True)),
                ('reactome', models.FloatField(max_length=7, null=True)),
                ('europepmc', models.FloatField(max_length=7, null=True)),
                ('expression_atlas', models.FloatField(max_length=7, null=True)),
                ('impc', models.FloatField(max_length=7, null=True)),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.Indication')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
            options={
                'db_table': 'indication_association',
            },
        ),
        migrations.CreateModel(
            name='Drugs2024',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=5, null=True)),
                ('complexity', models.FloatField(max_length=4, null=True)),
                ('tpsa', models.CharField(max_length=10, null=True)),
                ('drug_status', models.CharField(max_length=15, null=True)),
                ('approval_year', models.IntegerField(null=True)),
                ('indication_max_phase', models.IntegerField(null=True)),
                ('indication_status', models.CharField(max_length=15, null=True)),
                ('genetic_association', models.CharField(max_length=30, null=True)),
                ('affected_pathway', models.CharField(max_length=30, null=True)),
                ('somatic_mutation', models.CharField(max_length=30, null=True)),
                ('similarity_to_model', models.FloatField(max_length=4, null=True)),
                ('novelty_score', models.FloatField(max_length=4, null=True)),
                ('publication_count', models.IntegerField(max_length=4, null=True)),
                ('target_level', models.CharField(max_length=30, null=True)),
                ('disease_association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.IndicationAssociation')),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.Indication')),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
                ('moa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.LigandRole')),
                ('reference', models.ManyToManyField(to='common.Publication')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
            options={
                'db_table': 'drugs_new',
            },
        ),
        migrations.CreateModel(
            name='ATCCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.WebLink')),
                ('ligand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.Ligand')),
            ],
            options={
                'db_table': 'atc_codes',
            },
        ),
    ]
