# Generated by Django 3.2.25 on 2024-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_atccodes_drugs2024_indication_indicationassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs2024',
            name='publication_count',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='drugs2024',
            name='target_level',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
