# Generated by Django 3.2.25 on 2024-12-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20241204_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='atccodes',
            name='level_0',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='atccodes',
            name='level_1',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='atccodes',
            name='name_0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atccodes',
            name='name_1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
