# Generated by Django 3.2.25 on 2024-10-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_auto_20241004_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
