# Generated by Django 3.2.25 on 2024-10-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0021_auto_20240223_1135'),
        ('drugs', '0012_alter_indication_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicationAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_score', models.FloatField(max_length=7, null=True)),
                ('ot_genetics_portal', models.FloatField(max_length=7, null=True)),
                ('gene_burden', models.FloatField(max_length=7, null=True)),
                ('clingen', models.FloatField(max_length=7, null=True)),
                ('gene2phenotype', models.FloatField(max_length=7, null=True)),
                ('orphanet', models.FloatField(max_length=7, null=True)),
                ('genomics_england', models.FloatField(max_length=7, null=True)),
                ('uniprot_literature', models.FloatField(max_length=7, null=True)),
                ('uniprot_variants', models.FloatField(max_length=7, null=True)),
                ('sysbio', models.FloatField(max_length=7, null=True)),
                ('cancer_gene_census', models.FloatField(max_length=7, null=True)),
                ('cancer_biomarkers', models.FloatField(max_length=7, null=True)),
                ('intogen', models.FloatField(max_length=7, null=True)),
                ('eva', models.FloatField(max_length=7, null=True)),
                ('eva_somatic', models.FloatField(max_length=7, null=True)),
                ('chembl', models.FloatField(max_length=7, null=True)),
                ('slapenrich', models.FloatField(max_length=7, null=True)),
                ('crispr', models.FloatField(max_length=7, null=True)),
                ('crispr_screen', models.FloatField(max_length=7, null=True)),
                ('reactome', models.FloatField(max_length=7, null=True)),
                ('europepmc', models.FloatField(max_length=7, null=True)),
                ('expression_atlas', models.FloatField(max_length=7, null=True)),
                ('impc', models.FloatField(max_length=7, null=True)),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.indication')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
            options={
                'db_table': 'indication_association',
            },
        )
    ]
