# Generated by Django 3.2.25 on 2024-10-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0013_auto_20241018_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs2024',
            name='atc_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='drugs2024',
            name='disease_association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.indicationassociation'),
        ),
    ]
