# Generated by Django 3.2.25 on 2024-10-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0025_auto_20230831_1052'),
        ('common', '0006_releasestatistics_database'),
        ('drugs', '0014_auto_20241018_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATCCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.weblink')),
                ('ligand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ligand.ligand')),
            ],
            options={
                'db_table': 'atc_codes',
            },
        ),
    ]
