# Generated by Django 3.2.25 on 2024-10-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0015_atccodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugs2024',
            name='atc_code',
        ),
    ]
