# Generated by Django 2.2.17 on 2026-01-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_modality'),
        ('protein', '0020_auto_20250318_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'receptor_sense',
            },
        ),
        migrations.CreateModel(
            name='Chemotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('modality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemotypes', to='common.Modality')),
            ],
            options={
                'db_table': 'receptor_chemotype',
            },
        ),
        migrations.AddField(
            model_name='protein',
            name='chemotype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proteins', to='protein.Chemotype'),
        ),
        migrations.AddField(
            model_name='protein',
            name='sense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proteins', to='protein.Sense'),
        ),
    ]
